### PR TITLE
Formatted instructions added for installing pip on Windows

### PR DESCRIPTION
**Pull request by cjohnsonjava**

### CODE REVIEW

**Comment by kdflint** [comment]
Hi! We're forming a Python team. If you're interested in participating, let me know... One thing we particularly need is someone to assume the role of "Coach". This is not a technical responsibility, it's a logistical one. Managing the team calendar, etc. Nice space for a newbie. Couple hours a week at your convenience.

It was delightful to meet you on Saturday. Best!

Kathy

**Comment by cjohnsonjava** [comment]
Hi! Yes, I would be interested in participating. 

Thanks,
Coretta



     On Wednesday, July 29, 2015 11:57 AM, NorthBridge Technology Alliance <notifications@github.com> wrote:
   

 Hi! We're forming a Python team. If you're interested in participating, let me know... One thing we particularly need is someone to assume the role of "Coach". This is not a technical responsibility, it's a logistical one. Managing the team calendar, etc. Nice space for a newbie. Couple hours a week at your convenience.It was delightful to meet you on Saturday. Best!Kathy—

**Comment by kdflint** [comment]
excellent Coretta! Any chance you can join a video conference this Sat. at
5:00 pm?

If not, that's ok. Not everyone can come and there will be another meeting
scheduled.

Kathy
kathy.flint@northbridgetech.org

-- 



*Kathy Flint, CEO Northbridge Technology Alliance
http://northbridgetech.org
<http://NorthBridgeTech.org>kathy.flint@northbridgetech.org
<kathy.flint@northbridgetech.org> *

**Comment by cjohnsonjava** [comment]
Yes, I can join the video conference this Saturday.
Thanks,
Coretta
 


     On Thursday, July 30, 2015 9:00 PM, NorthBridge Technology Alliance <notifications@github.com> wrote:
   

 excellent Coretta! Any chance you can join a video conference this Sat. at
5:00 pm?

If not, that's ok. Not everyone can come and there will be another meeting
scheduled.

Kathy
kathy.flint@northbridgetech.org

-- 



*Kathy Flint, CEO Northbridge Technology Alliance
http://northbridgetech.org
<http://NorthBridgeTech.org>kathy.flint@northbridgetech.org
<kathy.flint@northbridgetech.org> *

**Pull request merged**
