### PR TITLE
Changes to Readme

### PR DESCRIPTION
**Pull request by Corvids**

### CODE REVIEW

**Comment by kdflint** [comment]
Hi! We're forming a Python team. If you're interested in participating, let me know... One thing we particularly need is someone to assume the role of "Coach". This is not a technical responsibility, it's a logistical one. Managing the team calendar, etc. Nice space for a newbie. Couple hours a week at your convenience.

It was delightful to meet you on Saturday. Best!

Kathy

**Comment by Corvids** [comment]
Hi,

I'd love to be a part of the Python team!  Please let me know how I can be
involved.

Thank you,
Jennifer

**Comment by northbridge-test** [comment]
Glad to hear, Jennifer!

What is your email address? This is so I can loop you in to the convo.

Kathy

-- 



*Kathy Flint, CEO Northbridge Technology Alliance
http://northbridgetech.org
<http://NorthBridgeTech.org>kathy.flint@northbridgetech.org
<kathy.flint@northbridgetech.org> *

**Comment by Corvids** [comment]
My email is: joonnifer@gmail.com

**Pull request merged**
